### ISSUE TITLE
在OSX平台下启动不了程序

### ISSUE THREAD

**Issue by w1ng** [jarjin/FinalFramework#10]
如题,看起来是新的库没有做OSX的适配,启动会报错
**EntryPointNotFoundException: luaL_getversion**

此外,Build Lua Files To Resource也会报错.内容如下:

Win32Exception: ApplicationName='/Users/xxx/FinalFramework/FirClient/Luac53/Mac/./luac', CommandLine=' -o /Users/xxx/FinalFramework/FirClient/Assets/StreamingAssets/Lua/Out/Main.lua.bytes /Users/xxx/FinalFramework/FirClient/Assets/StreamingAssets/Lua/Main.lua', CurrentDirectory='/Users/xxx/FinalFramework/FirClient/Luac53/Mac/', Native error= Cannot find the specified file

**Comment by jarjin** [comment]
mac + ios底层库还没空编译，家里mac机坏了

**Comment by w1ng** [comment]
> mac + ios底层库还没空编译，家里mac机坏了

有编译流程的话我这边可以编译完了之后提个pull request过来合并.

**Comment by jarjin** [comment]
> > mac + ios底层库还没空编译，家里mac机坏了
> 
> 有编译流程的话我这边可以编译完了之后提个pull request过来合并.

已经补上了
