### ISSUE TITLE
GameSetting打包报错

### ISSUE THREAD

**Issue by zhousong3333** [jarjin/FinalFramework#4]
Assets\Scripts\Common\GameSettings.cs(17,12): error CS0246: The type or namespace name 'TextureImporterFormat' could not be found (are you missing a using directive or an assembly reference?)

微信查无此人，微信群发个二维码呗。

**Comment by whl160118** [comment]
同求，新手正在学习 希望有个群交流一下

**Comment by jarjin** [comment]
已经修复了，更新即可
